name: "DotNet CI"
description: "Builds, tests, packages and publishes a dotnet based solution."

inputs:
  Solution: 
    description: "Optional solution to process, use this if you have multiple solutions."
    required: false
    default: "*.sln"

  DotNetSdkVersion:
    description: "Specific .NET SDK version to use."
    required: false
    default: ""
  WithNuGetCache:
    description: "Whether to cache NuGet packages."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: actions/setup-dotnet@v5
      if: ${{ inputs.DotNetSdkVersion != '' }}
      name: Use specific .NET SDK version ${{ inputs.DotNetSdkVersion }}
      with:
        dotnet-version: ${{ inputs.DotNetSdkVersion }}
        cache: ${{ inputs.WithNuGetCache == 'true' }}

    - name: DotNet Restore
      shell: bash
      run: dotnet restore ${{ inputs.Solution }}