name: "CI Branch conventions"
description: "Configure CI flags based on branches."

inputs:
  noTests:
    description: "Skip tests."
    required: false
    default: "false"
  prerelease:
    description: "Pre-release to trigger preparing packages."
    required: false
    default: "none"

outputs:
  noTests:
    description: "Skip tests."
    value: "test"
  prerelease:
    description: "Pre-release to trigger preparing packages."
    value: "default prerelease"
  withRelease:
    description: "Whether to perform a release."
    value: "withrelease flag"

runs:
  using: "composite"
  steps:
    - name: Detected prerelease build due to parameter.
      if: ${{ inputs.prerelease != null && inputs.prerelease != '' && inputs.prerelease != 'none' }}
      shell: bash
      run: |
        echo "withRelease=true" >> $GITHUB_OUTPUT
        echo "prerelease=${{ inputs.prerelease }}" >> $GITHUB_OUTPUT
        echo "noTests=true" >> $GITHUB_OUTPUT

    - name: Detected prerelease build for prerelease branch.
      if: ${{ (inputs.prerelease == null || inputs.prerelease == '' || inputs.prerelease == 'none') && startsWith(github.ref, 'refs/heads/prereleases/') }}
      shell: bash
      run: |
        echo "withRelease=true" >> $GITHUB_OUTPUT
        echo "prerelease=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        echo "noTests=true" >> $GITHUB_OUTPUT