name: "CI Branch conventions"
description: "Configure CI flags based on branches."

inputs:
  noTests:
    description: "Skip tests."
    required: false
    default: "false"
  prerelease:
    description: "Pre-release to trigger preparing packages."
    required: false
    default: "none"

outputs:
  withRelease:
    description: "Indicates if there should be a release"
    value: ${{ steps.convention.outputs.withRelease }}
  prerelease:
    description: "The pre-release version to use"
    value: ${{ steps.convention.outputs.prerelease }}
  noTests:
    description: "Skip tests."
    value: ${{ steps.convention.outputs.noTests }}

jobs:
  set-conventions:
    runs-on: ubuntu-latest
    steps:
      - name: Detected prerelease build due to parameter.
        id: "convention"
        if: (inputs.prerelease != null && inputs.prerelease != '' inputs.prerelease != 'none')
        run: |
          echo "withRelease=true" >> $GITHUB_OUTPUT
          echo "prerelease=$INPUTS_PRERELEASE" >> $GITHUB_OUTPUT
          echo "noTests=true" >> $GITHUB_OUTPUT
  
      - name: Detected prerelease build for prerelease branch.
        id: "convention"
        if: (inputs.prerelease == null || inputs.prerelease == '') && startsWith(github.ref, 'refs/heads/prereleases/')
        run: |
          echo "withRelease=true" >> $GITHUB_OUTPUT
          echo "prerelease=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          echo "noTests=true" >> $GITHUB_OUTPUT